version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: gwilym/wurstmeister-kafka-docker
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.28.28.236
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PROTOCOL_NAME: PLAINTEXT
      KAFKA_CREATE_TOPICS: "train:1:1,test:1:1,predict:1:1"
      KAFKA_PROTOCOL_NAME: PLAINTEXT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  zeppelin:
    image: xemuliam/zeppelin
    hostname: zeppelin
    ports:
      - "8080:8080"
      - "8443:8443"
      - "4040:4040"
    links:
      - elk
  elk:
    image: sebp/elk
    hostname: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
